platform :ios, '10.0'
use_frameworks!
inhibit_all_warnings!

target 'Kingfisher源码分析' do
   
  pod 'Kingfisher'

  

source 'https://github.com/CocoaPods/Specs.git'

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '5.0'
        end
    end
end

end
